-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 13, 2024 at 08:04 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `baza`
--

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `id` int(11) NOT NULL,
  `ime` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `prezime` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `korisnicko_ime` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `lozinka` varchar(255) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `razina` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`id`, `ime`, `prezime`, `korisnicko_ime`, `lozinka`, `razina`) VALUES
(15, 'Borevkovic', 'Marin', 'admin', '$2y$10$/q25PstwUXSZ9wDU4oMR0.B13xQruBPua8.nYYk9LH9rxoeC.WxW2', 1),
(16, 'Marin', 'Borevkovic', 'user', '$2y$10$8epEahrX..BQz5Zo7ksiUuz38YBFmUMcNGPWz2WVytrt6MrNSvlXy', 0);

-- --------------------------------------------------------

--
-- Table structure for table `vijesti`
--

CREATE TABLE `vijesti` (
  `id` int(11) NOT NULL,
  `datum` varchar(32) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `naslov` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `sazetak` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `tekst` text CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `slika` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `kategorija` varchar(64) CHARACTER SET latin2 COLLATE latin2_croatian_ci NOT NULL,
  `arhiva` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(34, '24.06.2023.', 'Oduševio na podiju', 'Jokić napravio totalni šou: S razglasa se "zakotrljao" Čolićev hit, a evo kako se Srbin potom "razbacao"', 'Trostruki MVP NBA lige i još uvijek aktualni prvak Nikola Jokić odmara u rodnom Somboru. Kako je Denver ove godine rano završio sezonu, Jokić se bacio na odmor uz konje i srpsku kafanu koje najviše voli. Nakon što je bio na aukciji konja i raftingu na Tari, na red je došla kafana i opuštanje uz dobro poznate hitove Zdravka Čolića. Jokić je na plesnom podiju pokazao da nije samo spretan u košarci, a okupljeni su bili oduševljeni njegovim potezima. Video je ubrzo postao viralni hit.Nakon NBA sezone, Jokić se okreće Srbiji i pripremama za Olimpijske igre. Srbija pripreme počinje 24. lipnja u Staroj Pazovi i tamo ostaje do 11. srpnja. Srbija će na Olimpijskim igrama koje počinju 26. srpnja igrati protiv Amerike, Južnog Sudana i pobjednika kvalifikacijskog turnira u Portoriku, a naši se susjedi nadaju zlatu.', 'jokic.jpg', 'SPORT', 0),
(35, '24.06.2023.', 'Meštrović odlazi', 'Ministar Beroš: "Od ravnatelja KBC-a Split tražio sam iste stvari kao od drugih ravnatelja..."', 'Pojavile su se informacije da ravnatelj KBC-a Split Julije Meštrović odlazi s te funkcije zbog pritisaka. On je od Upravnog vijeća zatražio razrješenje s dužnosti, što je za 24sata potvrdio ministar zdravstva Vili Beroš. - Upravno vijeće dobilo je zahtjev prof. dr. Julija Meštrovića, ravnatelja KBC-a Split, za razrješenjem radi njegove odluke da ode u mirovinu. Upravno vijeće poštuje želju prof. Meštrovića, a za sav dosadašnji rad i vođenje druge najveće bolnice u Hrvatskoj mu zahvaljuje. Zajedno smo prolazili kroz sva iskušenja, posebno tijekom epidemije Covida, i sve vrijeme je ravnatelj imao potporu Upravnog vijeća u cilju što veće učinkovitosti KBC-a Split. Vjerujem da je obavljanje odgovorne funkcije ravnatelja KBC-a Split, koji skrbi o velikom broju pacijenata sa širokog područja Dalmacije i otoka, od profesora Meštrovića zahtijevalo ogromnu energiju, ali treba istaknuti da smo sva pitanja zajednički rješavali, svatko u okvirima svojih nadležnosti i odgovornosti - kazao nam je ministar Beroš. Od ravnatelja KBC-a Split zahtijevao je, dodaje, kao i od svih drugih ravnatelja KBC-a u Hrvatskoj kao nositelja javnog zdravstvenog sustava, funkcionalnost bolnice, optimalno korištenje svih resursa na korist i dobrobit hrvatskih pacijenata.', 'mestrovic.jpg', 'POLITIKA', 0),
(36, '24.06.2023.', 'Françoise Hardy', 'Preminula je legendarna pjevačica, Mick Jagger ju je nazvao "idealnom ženom",', 'Françoise Hardy, francuska kantautorica čiji su je melankolični glas, senzualna ljepota i smisao za stil učinili međunarodnom senzacijom u tinejdžerskim godinama, zadivivši modne dizajnere i slavne glazbenike kao što su Bob Dylan i David Bowie, umrla je u dobi od 80 godina. Vijest o smrti pop ikone objavio je njezin sin, pjevač i gitarist Thomas DuTronc, na Instagramu u srijedu. Bolovala je od karcinoma koji joj je dijagnosticiran još 2004. Poznata po svojim melankoličnim baladama, simbolizirala je francuski Yé-yé pop pokret, tako nazvan zbog svog naginjanja engleskoj glazbi. Među njezine najpoznatije pjesme spadaju Tous les garçons et les filles), Comment te dire adieu i Mon amie la rose. Najveći britanski hit bio joj je All Over The World, verzija njezine pjesme Dans le monde entier na engleskom jeziku, koja je u lipnju 1965. dosegnulaa 16. mjesto na top ljestvici. Hardy je rođena u Parizu pod nacističkom okupacijom 1944. godine, a odgojila ju je majka. Kao i mnoge djevojke u to vrijeme, odrastala je slušajući Elvisa Presleyja, Cliffa Richarda i druge američke i britanske zvijezde na Radio Luksemburgu, a sa samo 17 godina potpisala je svoj prvi diskografski ugovor. Glazbeni proboj imala je 1962. s jednostavnom, tužnom pjesmom, Tous les garçons et les filles, kada je pjevala o svim dječacima i djevojčicama kako hodaju ruku pod ruku, dok je ona "hodala sama ulicama". Bio je instant hit u Francuskoj a probio se i na ljestvice u Velikoj Britaniji.', 'pjevacica.jpg', 'KULTURA', 0),
(37, '24.06.2023.', 'Moguće kombinacija', 'Što to čeka Hrvatsku na Euru? Budemo li treći u skupini, smiješi nam se prilika za reprizu velike pobjede', 'Španjolska 15. lipnja, Albanija 19. lipnja i za kraju Italija 24. lipnja. Tako izgleda raspored Hrvatske u skupini B Europskog prvenstva u Njemačkoj. Za 13 dana saznat ćemo kako su Vatreni odradili posao, jesu li prošli u osminu finala ili se oprostili već u prvoj fazi natjecanja. Ostvare li Dalićevi momci uspjeh i uđu među 16 najboljih, trenutačno je čak 16 mogućih suparnika s kojima mogu u borbu za mjesto u četvrtfinalu. Kao prvi igrali bi 30. lipnja u Kölnu, kao drugi dan ranije u Berlinu, a kao treći početkom srpnja. Postoje dvije mogućnosti, da igraju protiv osvajača skupine F 1. srpnja u Frankfurtu ili protiv najboljeg iz skupine E 2. srpnja u Münchenu. Zasad je jedino jasno da 2. mjesto u skupini B donosi dvoboj s drugoplasiranim iz skupine A u kojoj su Njemačka, Škotska, Mađarska i Švicarska. Računamo li da će tu skupinu osvojiti domaćin Njemačka, takav rasplet u osmini finala uopće ne bi bio loš. U četvrtfinalu bi potom, barem prema papirnatom pogledu na favorite, Vatrene mogla dočekati Engleska.Prvoplasirani iz naše skupine morat će pričekati na rasplete u ostalim skupinama. Mogući suparnici su treći iz skupine A (ako najbolji treći budu iz skupina A, B, C i D ili A, B, C i E ili A, B, C i F), skupine D (ako treći najbolji budu iz skupina A, B, D i E ili A, B, D i F), skupine E (ako treći najbolji budu iz skupina A, B, E i F ili A, C, D i E ili A, C, E i F ili A, D, E i F ili B, C, D i E) i skupine F (ako treći najbolji budu iz skupina A, C, D i F ili B, C, D i F ili B, C, E i F ili B, D, E i F ili C, D, E i F). Jako komplicirano, zato se teško baviti ozbiljnijim kalkulacijama, a matematički su najveće šanse da će suparnik stići iz skupina E ili F.', 'hrv_euro.jpg', 'SPORT', 0),
(38, '24.06.2023.', 'Poljoprivreda neće u Slavoniju?', 'Josip Dabro o prvim potezima i selidbi ministarstva: Jedno su želje, a drugo su mogućnosti', 'Ministar poljoprivrede Josip Dabro kao prioritete svog rada ističe administrativno rasterećenje poljoprivrednika i postizanje samodostatnosti u proizvodnji hrane, a za preseljenje ministarstva u Osijek kaže da bi to unatoč želji, bilo logistički i kadrovski teško realizirati u kratkom roku. Upitan koji su mu prvi koraci i prioriteti, Hini je odgovorio da će se prvenstveno usmjeriti na administrativno rasterećenje poljoprivrednika u okvirima uredbi EU-a. To će biti jedna od prvih tema kojima ću se posvetiti, rekao je Dabro za Hinu, u povodu preuzimanja poljoprivrednog vladinog resora. Najavio je da će u tjednima koji slijede razgovarati s predstavnicima poljoprivrednika, "biti na terenu te osluškivati njihove potrebe i sukladno tome djelovati". "Poduzet ću prve korake za dobrobit sela, u najkraćem mogućem roku. Zbog poljoprivrednika sam tu, o njihovim potrebama će ovisiti moji prvi koraci, a neki su već započeti", rekao je. Kaže da će učiniti sve kako bi se preokrenuli negativni trendovi u djelatnostima s padom proizvodnje. U planu su, kako je naveo, izmjene Strateškog plana Zajedničke poljoprivredne politike (ZPP) kojima se olakšava korisnicima korištenje sredstava fondova, a razgovarat će se i o novim mjerama koje će doprinijeti rastu poljoprivredne proizvodnje.', 'poljoprivreda.jpg', 'POLITIKA', 0),
(39, '24.06.2023.', 'Iz pokreta otpora', 'Prodaje se građanska vila iz 1930-ih, po nižoj cijeni', 'Izložba kustosice Leile Topić sjajno se uklopila u ovogodišnje, odlično izdanje Subversivea, a otvorena je u MSU. Naslovni rad daje kritički odnos prema ženama u NOB-u. Ovim citatom počinje video "Crvena, da te nema..." naziv je izložbe koja se do 28. lipnja može pogledati u MSU u Zagrebu, kustosice Leile Topić. Izložba je otvorena uz 17. Subversive Film Festival. Kolege su pisali o filmovima koji se prikazuju na festivalu, među njima je i "Radnička klasa ide u pakao" Mladena Đorđevića, koji se nametnuo kao hit, ali i o gostovanju Angele Davis koja je rasprodala manji, predviđeni prostor pa se preselila u Lisinski i oduševila. Rekla je među ostalim, kako sam pročitala od onih koji su u petak navečer bili na predavanju, da je potrebna kritična masa kako bi se promjena dogodila. To je rečenica koju bi svakako trebalo promatrati i u kontekstu najnovije političke apatije, izlaska malog broja birača na izbore... ', 'vila1930.jpg', 'KULTURA', 0),
(41, '24.06.2023.', 'Penavi se ne javlja', 'Nakon vožnje u Ferrariju, Stjepo Bartulica je otišao u Bruxelles: "Sjedio je sam i zamišljen..."', 'Ovo je nešto što DP nije, ne može biti i ne smije biti. Očekujem i dalje Bartulicu da izađe pred vas, obrazloži svoj kut i da se ispriča za ove najnovije informacije koje smo doznali. Kad sam vidio taj Ferrari, kao većina normalnih ljudi sam mislio da je to vozilo nekog gosta. Sad to izgleda kao simpatična priča. Nije mi poznat taj detalj o kriminalnom dosjeu ljudi koji su došli s njim, ispričao je u srijedu novinarima Ivan Penava.  Priča oko Bartulice i crvenog Ferrarija i dalje se ne stišava. Na EU Parlamentarnim izborima je osvojio mandat i zastupničko mjesto u Bruxellesu, da bi se zatim u stožer dovezao i odvezao u Ferrariju. Dodao je Penava kako mu se Stjepo Bartulica zadnja dva dana ne javlja, kao niti ostatku stranačkog vrha. Za to vrijeme, spomenuti novopečeni europarlamentarac snimljen je danas u ranim poslijepodnevnim satima u Europskom parlamentu u Bruxellesu, doznaje Telegram.', 'penavi.jpg', 'POLITIKA', 0),
(42, '24.06.2023.', 'Kakav tandem', 'Bomba iz Španjolske: svježe okrunjeni kralj i neprikosnoveni rekorder Roland Garrosa udružit će snage u Parizu', 'Svježe okrunjeni kralj i neprikosnoveni rekorder Roland Garrosa udružit će snage na pariškoj zemlji. Carlos Alcaraz i Rafael Nadal natjecat će se u konkurenciji parova na nadolazećim Olimpijskim igrama u Parizu. Nakon što je 21-godišnjak prije četiri dana osvojio prvi Roland Garros, što mu je bila ukupno treća Grand Slam titula, od 27. srpnja vratit će se na mjesto sreće sa 17 godina starijim kolegom, s igračem koji je 14 puta pokorio Pariz. - Nisam uspio osvojiti medalju kao igrač, nadam se da ću uspjeti kao kapetan momčadi. Uvjereni smo da možemo osvojiti i više od jedne medalje - komentirao je David Ferrer, nekoć treći igrač svijeta, a danas u službi izbornika reprezentacije.Obje španjolske zvijezde natjecat će se i u pojedinačnoj konkurenciji, a u karijeri su se sretali triput na suprotnim stranama terena, uz dvije pobjede iskusnijeg igrača. Nakon osvajanja novog Grand Slama, Alcaraz nije skrivao oduševljenje uoči povratka u Francusku. - Bit će to poseban turnir, moje prve Olimpijske igre nakon osvajanja mog prvog Roland Garrosa. Borit ću se za zlatnu medalju za svoju zemlju, igrat ću u paru sa svojim idolom... U takve ću stvari vjerovati tek kada ih i iskusim - rekao je za L"Equipe. Dok Carlos nema iskustva na Igrama, Nadal je 2008. uzeo zlatnu medalju u Pekingu, u pojedinačnoj konkurenciji, dok je u Riju 2016. osvojio najsjajnije odličje u konkurenciji parova s Marcom Lópezom.', 'tenis.jpg', 'SPORT', 0),
(45, '24.06.2023.', 'Nisu prošli šarlatani', 'Andrej Plenković o EU izborima: Građani su ovog puta dali crveni karton prodavačima magle', '"Ima razloga mijenjati. Prvo treba promijeniti iznos novaca, koji je premali za kampanju i skratiti kampanju radikalno. Ova je trajala 45 dana, a imate svega 500.000 eura na raspolaganju, to je danas, s promijenjenim uvjetima oglašavanja, gotovo nemoguće", izjavio je premijer Andrej Plenković na konferenciji za novinare nakon sastanka parlamentarne većine u Banskim dvorima. Smatra da se treba promijeniti medijsko praćenje izborne kampanje za europske izbore jer su važne teme mediji potpuno izignorirali i bavili se drugim, pretežito "nacionalnim temama". Kao da izbora nije ni bilo. Išao sam u županije, na skupove, i imao sam dojam da nikome nije palo na pamet pitati pitanje o europskim izborima, rekao je Plenković. "Dio medijskoga prostora bio je obasut naknadama i plaćama zastupnika u EU, kao da samo Hrvati imaju takve plaće. Način na koji je bilo to pisano je bio odvraćajući, što znači da ne gledamo sadržaj nego posljedice koristi", dodao je. ', 'plenkovic_izbori.jpg', 'POLITIKA', 1),
(46, '24.06.2023.', 'Pakleni napadač', 'Tvrdoglav kao bik, opasan kao vrag', 'Njemu to doista nije "bed". Otići iz jedne druge na dno druge druge lige, samo da dobije priliku. Da radi "kao pas", kako su ga jednom opisali treneri iz mlađih kategorija, da se trsi i bori. I izbori. Njegov kompletni životni i nogometni put zapravo je identičan onome koji je prošao od Katara pa sve do "one" Armenije i sada ovog Eura. S dna liste, s koje je nakon Mundijala ispao, samo da bi nastavio šutjeti i "rintati", samo da bi se izborio za novu šansu. I to bez krivih osjećaja, grubih glagola, negodovanja ili javnih, pa i intimnih vapaja ili apela. - Ja ću se boriti pa ako poziv dođe, bit ću presretan kao što su sada sigurno oni koji su dobili priliku biti na mom mjestu i staviti se u službu reprezentacije - rekao mi je jednom prilikom Ante Budimir. Da, taj 32-godišnjak upravo ovih dana sumira svoju karijeru. I Goricu, i zaprešićki Inter, i Lokomotivu, i St. Pauli, i Crotone, i Sampdoriju, i Mallorcu i Osasunu. I padove, i upornost do krajnjih granica i uspone. Koji su sada sublimirani u gotovo općem konsenzusu, temeljenom isključivo na argumentu - igre. A on govori da bi Ante Budimir trebao biti starter u utakmici protiv Španjolske, na hrvatskom otvaranju Eura u Berlinu. Dalić je od Katara do Njemačke dugo tražio nove napadačke opcije, zvonili su telefoni brojnih igrača, no onda je na kraju shvatio da tamo u Pamploni postoji jedan igrač, tvrdoglav i uporan baš kao bik. I da čovjek igra nogomet karijere. Trpa kao na traci, ima silno velike pomake u igri, a golovi i povjerenje napokon su ga napunili samopouzdanjem. Takvom, uz urođenu a sada dorađenu agresivnost i set vještina koje Daliću nude novu, drugačiju vizije igre, savršeno mu, zapravo, pristaje Mandžukićeva "sedamnaestica" na dresu, koju je nosio u pobjedi protiv Armenije, s pogotkom koji nas je i odveo na Euro.', 'budimir.jpg', 'SPORT', 1),
(47, '24.06.2023.', 'Prvi na svijetu', 'Pljušte reakcije na spomenik Mercedesu u Imotskom: Oglasio se i naš poznati dizajner', 'Ljubičića je djelo podsjetilo na rad glasovitog konceptualnog umjetnika. Nakon što je u subotu svečano u Imotskom inauguriran prvi spomenik Mercedesu na svijetu, kao posveta "statusnom simbolu imotskih iseljenika", pojavile su se, očekivano, i brojne reakcije na društvenim mrežama. Oglasio se i naš poznati dizajner Boris Ljubičić koji je na svom Facebooku postavio pitanje: "Što nedostaje ovom radu Brace Dimitrijevića?" "Da, našalio sam se da je to rad Brace Dimitrijevića. Ima taj neki karakter, ali u negativnom smislu", kaže Ljubičić o svojoj neobičnoj usporedbi sa znamenitim konceptualnim umjetnikom. Objavu je popratio fotografijama imotskog kamenog Mercedesa 115 i svojim plakatom za Međunarodni dan muzeja iz 2004. godine u kojem je sučelio Mercedesov znak i Sinjsku alku. Htio je ukazati, kaže, da tom Mercedesu ostvarenom "od ljutog imotskog kamena" u prirodnoj veličini fali njegov vizualni identitet, nedostaje mu njegov prepoznatljivi znak, što su uočili i njegovi pratitelji. "Vjerojatno nemaju dozvolu od Mercedesa", zaključio je jedan u svom komentaru. "Nedorečen u sadržaju, maštovit u izričaju", "Vjerujem da je klijent bio dosta konzervativan", "Ima sve! Čak i gay zastavu. Izgleda kao da je radioaktivna prašina pala na njega", neki su od komentara na spomenik čiji je autor Mislav Rebić, a klesali su ga studenti kiparstva iz Hrvatske i inozemstva pod vodstvom mladog kipara Roka Rebića.', 'kamena_mecka.jpg', 'KULTURA', 0),
(48, '24.06.2023.', 'Kritika grada', 'Prepuna kanta za smeće koju svaki dan gledate u svojem kvartu? Ne, minijatura od samo par centimetara....', 'Riječ je o izložbi "Kexer: graffiti u minijaturama" koja je otvorena do 12. lipnja galeriji Siva u prostoru Medike. Kada mi je street art umjetnik Krešimir Golubić poslao fotografiju smeća, mislila sam da me slikovno podsjeća na stanje kvarta u kojemu ja živim, a on radi. Takvi nam kvartovski prizori, naime, nisu strani. No ispostavilo se da je riječ o fotografiji s izložbe i prikazuje smeće visoko samo nekoliko centimetara koje se nalazi na maketi kuće. Riječ je o izložbi "Kexer: graffiti u minijaturama" koja je otvorena do 12. lipnja u prilično agilnoj galeriji Siva u prostoru Medike, a riječ je o čestom okupljalištu protagonista alternativne kulture koje je potpuno ispisano grafitima. Dok sam obilazila izložbu, Kexer mi je objašnjavao da je projekt počeo od jedne narudžbe te da na njemu radi tri godine, malo po malo. Koristi različite materijale, od recikliranih komada drva, plastike, metala i stiropora uz upotrebu 3D printera te specijaliziranih maketarskih materijala i boja. Ova izložba prikazuje minijaturne, ulične segmente stvarnih zagrebačkih lokacija te nekoliko fiktivnih izvedenih u tzv. diorami ili vinjeti. U prvom su planu gradske fasade te derutni, napušteni privatni i gradski prostori koji su, tumači, "tijekom godina dobili kreativni makeover u obliku grafita i potpisa". Prepoznat ćete mnoge motive, od znaka Hollywood na brdu, preko Lunarovih mačaka i oslikanih vagona. Uz svaki je rad QR kod koji vas vodi na stvarnu lokaciju gdje se grafit nalazi, ako je on tema. Radovi su, piše uz izložbu, usredotočeni i na često zanemarene aspekte urbanog okoliša poput prljavštine, hrđe, raspadanja fasade, odbačenih cigareta i smeća, a sve je izvedeno u mjerilu 1:35.', 'kanta.jpg', 'KULTURA', 1),
(49, '24.06.2023.', 'Pogledajte transformaciju', 'Kako je rasla Ivana Knoll? Od anonimne navijačice iz Rusije do slave i SAD-a: "Stižem na Euro!"', 'Kad igra Hrvatska ona je tu. Ona je atraktivna navijačica koja je oduševila velik dio Hrvata, ali i svijet svojim stajlinzima i navijanjem. Naravno, radi se o Ivani Knoll, poznatijoj i kao Knoll Doll. Manekenstvom se bavi od 18. godine, a snimila je nekoliko reklama i nosila brojne revije. Na Instagramu je prati više od tri milijuna pratitelja, a privlačna Ivana oduševljava pratitelje svojim bujnim oblinama i uskim strukom. Bila je i na izboru za Miss Hrvatske kao predstavnica dijaspore postala je 2016. godine. Ivana je rođena u Njemačkoj, a u Hercegovini je živjela sa svojim roditeljima gdje je pohađala Opću gimnaziju. Godinama se bavila i plesom, a velika je obožavateljica svih vrsta trbušnog plesa i plesa na šipci. Tamo 2016. godine tvrdila je kako je uspjela upoznati velik broj država, a da joj je cilj posjetiti sve.', 'ivana_knoll.jpg', 'ZABAVA', 0),
(50, '24.06.2023.', 'Nikad iskrenija', 'Žanamari otkrila detalje iz privatnog života o kojem rijetko kada priča: "Bila sam preopsesivna..."', 'Pjevačica Žanamari Perčić izvela je svoju pjesmu "24/7" na CMC festivalu u Vodicama pa za IN magazin progovorila o svoj ljubavi prema teretani, kćerkici Gabrijeli i suprugu Mariju, poznatijem kao Joshua Macks. "Cijeli život sam nekako u teretani, ali otkad sam rodila nisam baš bila redovita, malo sam bila preopsesivna majka", kazala je pjevačica. "Morala sam biti s djetetom 24 sata dnevno i na kraju kad sam počela ići u teretanu, tih 3 sata dnevno su mi bili jedini koje sam imala za sebe. Iako, Gabi već ima devet godina pa sad i ona sa mnom ide u teretanu! Sad smo ipak 24 sata zajedno", dodala je. Žanamari o svojoj kćerkici za koju misli da će biti umjetnica. "Gabi je toliko talentirana, ona i piše pjesme, fenomenalno pjeva, ali primijetila sam da ne voli biti u centru pozornosti. U školskim predstavama se ne gura u prve redove, onako tiha je, samozatajna, ali jako kreativna. Voli crtati, stalno nešto radi, kuća mi je puna boja, ljepila, raznih papira, onih platna za crtanje...", objasnila je pjevačica. Inače, Žanamari ne voli previše govoriti o svom privatnom životu, a na taj je način počela razmišljati kada se ostvarila kao majka. "Otkad sam rodila štitim i to dijete, objavila sam ju možda dva, tri puta u devet godina. Počela sam drukčije razmišljati kad sam postala majka, ali i s druge strane kad si 20 godina na sceni, poželiš jednostavno neke stvari zadržati za sebe", kazala je.', 'zanamari.jpg', 'ZABAVA', 0),
(51, '24.06.2023.', 'Poslušajte ga', 'Luka Bulić ima novi "Bullhit" kao podršku Vatrenima uoči Eura', 'Antena Zagreb ima novi Bullhit! Luka Bulić otpjevao je nabrijavajuću stvar za podršku hrvatskoj reprezentaciji na Europskom nogometnom prvenstvu u Njemačkoj, a kao ideju za to Luka je iskoristio podlogu popularnog hita "Rim Tim Tagi Dim" s kojim se Hrvatska proslavila na Eurosongu i diljem svijeta. "Ovaj "Bullhit" je nastao, to jest ideja, već za vrijeme Eurosonga, zato što se iskristaliziralo "Dream Team, Zabij Im" kao super zamjena za "Rim Tim Tagi Dim". Osim toga pjesma je ujedinila Hrvatsku baš kao što to čini i naša repka. Kontaktirao sam Baby Lasagnu kojem se ideja svidjela. Njegova pjesma je odlična, naši nogometaši su odlični, a "Bullhit" je nastao kao dobitna kombinacija. Nadam se da će donijeti lijepe osjećaje svima koji navijaju i da će još više potaknuti euforiju koja je već prisutna posvuda.Za dalje ćemo vidjeti, ovisno o tome kako će se razvijati situacija u Njemačkoj, tako će se dalje razvijati i "Bullhitovi". To više nije na nama, nego na našim dečkima, ali vjerujemo da će ih biti još puno", poručio je Luka. Hrvatska je plesala u "Rim Tim Tagi Dim" ritmu kao znak podrške Baby Lasagni na Eurosongu, a sada će plesati u ritmu "Dream Team, Zabij Im" kao znak podrške našim nogometašima.', 'pjesma.jpg', 'ZABAVA', 0),
(52, '24.06.2023.', 'Usponi i padovi', 'Šuška se o burnoj vezi slavnog glazbenika i glumice, prijatelji tvrde: "Pomirili su se, ponovno su zajedno"', 'Dakota Johnson i Chris Martin potajno su prekinuli svoju vezu, ali su se u međuvremenu pomirili i sada su ponovno zajedno, tvrde oni bliski poznatom paru. Naime, ova 34-godišnja glumica i 47-godišnji frontmen Coldplayja skrivali su poteškoće u svojoj vezi, ali sada su se vratili na pravi put, kažu izvori za časopis People. Prema Daily Mailu i spomenutom izvoru, "imali su uspona i padova, ali sada su se definitivno vratili u igru", ljubavno, ali i sa svojim karijerama. Dakoti je nedavno krenulo prikazivanje HBO serije "Am I OK?", a na Tribeca Film Festivalu u ponedjeljak premijerno je prikazan njen najnoviji igrani film "Daddio". S druge strane, Chris je trenutačno pri kraju svoje turneje "Music of the Spheres" s Coldplayom, koja je započela u ožujku 2022. godine, Posljednji put je ovaj skroman par viđen zajedno u veljači tijekom putovanja u Puerto Vallartu u Meksiku. Tjednima kasnije objavljeno je da su se "zaručili" još u ožujku. Tada je rečeno da je pjevač Coldplaya zaprosio glumicu već ranije i da ima "blagoslov" svoje bivše supruge Gwyneth Paltrow (51) i njihove djece, kćeri Apple (19) i sina Mosesa (17). Par je svoju romansu držao u tajnosti otkako su započeli vezu prije šest godina. - Bili su oduševljeni jedno drugim od prvog dana, pa je poduzimanje sljedećeg koraka bilo neizbježno. Njima se ne žuri s planiranjem vjenčanja, već samo uživaju u vremenu provedenom zajedno - tvrdi izvor.', 'veza.jpg', 'ZABAVA', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `korisnicko_ime` (`korisnicko_ime`);

--
-- Indexes for table `vijesti`
--
ALTER TABLE `vijesti`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `vijesti`
--
ALTER TABLE `vijesti`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
